### ISSUE TITLE
[Feature Suggestion] CanvasGroup, Events, Loops

### ISSUE THREAD

**Issue by digiwombat** [Misteeps/Ease-Transitions-System#5]
Hey!

Great work on the system so far! It's got a lot of very helpful stuff and the ability to test in editor is a fantastic time saver. A few things I think would really make this usable for broader cases, though:

### CanvasGroup Control

Probably fairly simple. It's just a float value, but it's a very common way of dealing with UI fading.

### Start and End events for either tweens or tween groups.

This one is a pretty crucial piece of of the pie for me. To reference DoTween, it's got OnKill, OnComplete, OnUpdate and a bunch of other useful functions. I'm not sure all those are necessary for what you've got here, since there's a focus on group transitions (which is great for UI work), but I do think at the very least being able to track group start and group end are a bare minimum for things like re-enabling input or moving to the next sequence or even just showing and hiding GameObjects.

### Looping Tweens

Maybe I just missed these but looping tweens and the various loop types seem like they would be fairly valuable here.

**Comment by Misteeps** [comment]
... I'm a bit embarrassed to only be finding out that canvas group exists now.
All that time that I have faded UI objects one by one could have been a lot easier xD

### CanvasGroup and Camera fields have been added to the "Camera & CanvasGroup Components" branch.

Start/End events and loops are great ideas and I'll be working on them, but they'll take a bit to implement.

**Comment by Misteeps** [comment]
### Play, Reverse, Pause, Loop functionality has been added to the master branch :D

Every transition value now has a state (tValue.state) to either set or check if its
- going forward
- going backward
- paused
- has ended

Transition values can now be looped on repeat or back & forth
And the option to add a delay between loops will probably be added soon.

Transition objects are a bit harder to track as all of its tValues are independent from the object itself, but you can check if an object is done transitioning with tObject.values:
```csharp
TransitionObject tObject;
// Apply Transitions

if (tObject.values == 0)
    // tObject is done transitioning
```

Editor window functionality and documentation on the new features will be updated soon
